---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - heterflow.heterflow.com
  resources:
  - realtimejobdispatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heterflow.heterflow.com
  resources:
  - realtimejobdispatchers/finalizers
  verbs:
  - update
- apiGroups:
  - heterflow.heterflow.com
  resources:
  - realtimejobdispatchers/status
  verbs:
  - get
  - patch
  - update
