package def

type BehaviorInstClass int8
type TechInstClass int8
type BehaviorInstManager []BehaviorInstClass
type TechInstManager []TechInstClass

const (
	Transmission BehaviorInstClass = iota
	IO
	Arithmetic
	Logical
	String
	ProgramTransfer
	Interrupt
	Pseudo
	ProcessorControl

	VIRTUALIZATION TechInstClass = iota
	GP                           //通用指令
	GP_EXT                       //扩展通用指令
	GP_IN_OUT                    // 输入/输出指令
	FPU                          // 浮点运算单元指令
	MMX                          //多媒体扩展指令
	STATE                        //状态控制指令
	SIMD                         //单指令多数据指令
	SSE                          //流SIMD扩展指令
	SCALAR                       //标量指令
	CRYPTO_HASH                  //加密散列指令
	AVX                          //高级向量扩展指令
	AVX512                       //高级向量扩展512指令
	MASK                         //掩码指令
	AMX                          //高级矩阵扩展指令
)

var (
	X86X64ProcessorActionOrientedSet = map[string]BehaviorInstManager{
		"mov":             {Transmission},
		"movsxd":          {Transmission},
		"movsx":           {Transmission},
		"movzx":           {Transmission},
		"push":            {Transmission},
		"pop":             {Transmission},
		"pusha":           {Transmission},
		"popa":            {Transmission},
		"popad":           {Transmission},
		"bswap":           {Transmission},
		"xchg":            {Transmission},
		"cmpxchg":         {Transmission},
		"xadd":            {Transmission},
		"xlat":            {Transmission},
		"in":              {IO},
		"out":             {IO},
		"lea":             {Transmission},
		"lds":             {Transmission},
		"les":             {Transmission},
		"lfs":             {Transmission},
		"lgs":             {Transmission},
		"lss":             {Transmission},
		"lahf":            {Transmission},
		"sahf":            {Transmission},
		"pushf":           {Transmission},
		"popf":            {Transmission},
		"popd":            {Transmission},
		"pushd":           {Transmission},
		"add":             {Arithmetic},
		"adc":             {Arithmetic},
		"inc":             {Arithmetic},
		"aaa":             {Arithmetic},
		"daa":             {Arithmetic},
		"sub":             {Arithmetic},
		"sbb":             {Arithmetic},
		"dec":             {Arithmetic},
		"nec":             {Arithmetic},
		"cmp":             {Arithmetic},
		"aas":             {Arithmetic},
		"das":             {Arithmetic},
		"mul":             {Arithmetic},
		"imul":            {Arithmetic},
		"div":             {Arithmetic},
		"idiv":            {Arithmetic},
		"aam":             {Arithmetic},
		"aad":             {Arithmetic},
		"cbw":             {Arithmetic},
		"cwd":             {Arithmetic},
		"cwde":            {Arithmetic},
		"cdq":             {Arithmetic},
		"and":             {Logical},
		"or":              {Logical},
		"xor":             {Logical},
		"not":             {Logical},
		"test":            {Logical},
		"shl":             {Logical},
		"sal":             {Logical},
		"shr":             {Logical},
		"sar":             {Logical},
		"rol":             {Logical},
		"ror":             {Logical},
		"rcl":             {Logical},
		"rcr":             {Logical},
		"ds":              {String},
		"es":              {String},
		"cx":              {String},
		"al":              {String},
		"ax":              {String},
		"movs":            {String},
		"movsb":           {String},
		"movsw":           {String},
		"movsd":           {String},
		"cmps":            {String},
		"cmpsb":           {String},
		"cmpsw":           {String},
		"scas":            {String},
		"lods":            {String},
		"lodsb":           {String},
		"lodsw":           {String},
		"lodsd":           {String},
		"stos":            {String},
		"rep":             {String},
		"repe":            {String},
		"repne":           {String},
		"repc":            {String},
		"repnc":           {String},
		"int":             {Interrupt},
		"into":            {Interrupt},
		"iret":            {Interrupt},
		"hlt":             {Interrupt},
		"wait":            {Interrupt},
		"esc":             {Interrupt},
		"lock":            {Interrupt},
		"nop":             {Interrupt},
		"stc":             {Interrupt},
		"clc":             {Interrupt},
		"cmc":             {Interrupt},
		"std":             {Interrupt},
		"cld":             {Interrupt},
		"sti":             {Interrupt},
		"cli":             {Interrupt},
		"dw":              {Pseudo},
		"proc":            {Pseudo},
		"endp":            {Pseudo},
		"segment":         {Pseudo},
		"assume":          {Pseudo},
		"ends":            {Pseudo},
		"end":             {Pseudo},
		"loop":            {ProcessorControl},
		"loope":           {ProcessorControl},
		"loopz":           {ProcessorControl},
		"loopne":          {ProcessorControl},
		"loopnz":          {ProcessorControl},
		"jcxz":            {ProcessorControl},
		"jecxz":           {ProcessorControl},
		"jmp":             {ProgramTransfer},
		"call":            {ProgramTransfer},
		"ret":             {ProgramTransfer},
		"retf":            {ProgramTransfer},
		"jae":             {ProgramTransfer},
		"jnb":             {ProgramTransfer},
		"jb":              {ProgramTransfer},
		"jnae":            {ProgramTransfer},
		"jbe":             {ProgramTransfer},
		"jna":             {ProgramTransfer},
		"jg":              {ProgramTransfer},
		"jnle":            {ProgramTransfer},
		"jge":             {ProgramTransfer},
		"jnl":             {ProgramTransfer},
		"jl":              {ProgramTransfer},
		"jnge":            {ProgramTransfer},
		"jle":             {ProgramTransfer},
		"jng":             {ProgramTransfer},
		"je":              {ProgramTransfer},
		"jz":              {ProgramTransfer},
		"jne":             {ProgramTransfer},
		"jnz":             {ProgramTransfer},
		"jc":              {ProgramTransfer},
		"jnc":             {ProgramTransfer},
		"jno":             {ProgramTransfer},
		"jnp":             {ProgramTransfer},
		"jpo":             {ProgramTransfer},
		"jns":             {ProgramTransfer},
		"jo":              {ProgramTransfer},
		"jp":              {ProgramTransfer},
		"jpe":             {ProgramTransfer},
		"js":              {ProgramTransfer},
		"adcx":            {Arithmetic},
		"addl":            {Arithmetic},
		"addq":            {Arithmetic},
		"addsd":           {Arithmetic},
		"addss":           {Arithmetic},
		"adox":            {Arithmetic},
		"andn":            {Logical},
		"andpd":           {Logical},
		"andq":            {Logical},
		"bt":              {Arithmetic},
		"btc":             {Arithmetic},
		"btr":             {Arithmetic},
		"bts":             {Arithmetic},
		"cltd":            {Arithmetic},
		"cmpb":            {Arithmetic},
		"cmpl":            {Arithmetic},
		"cmpnltsd":        {Arithmetic},
		"cmpq":            {Arithmetic},
		"cmpw":            {Arithmetic},
		"comisd":          {Arithmetic},
		"cqto":            {Arithmetic},
		"cvtsd2si":        {Arithmetic},
		"cvtsi2sd":        {Arithmetic},
		"cvtsi2ss":        {Arithmetic},
		"cvtss2sd":        {Arithmetic},
		"decl":            {Arithmetic},
		"decq":            {Arithmetic},
		"divsd":           {Arithmetic},
		"divss":           {Arithmetic},
		"incl":            {Arithmetic},
		"incq":            {Arithmetic},
		"paddd":           {Arithmetic},
		"palignr":         {Arithmetic},
		"shld":            {Arithmetic},
		"shrd":            {Arithmetic},
		"subq":            {Arithmetic},
		"subsd":           {Arithmetic},
		"subss":           {Arithmetic},
		"mulq":            {Arithmetic},
		"mulsd":           {Arithmetic},
		"mulx":            {Arithmetic},
		"psubd":           {Arithmetic},
		"ucomisd":         {Arithmetic},
		"ucomiss":         {Arithmetic},
		"vaddsd":          {Arithmetic},
		"vfmadd213sd":     {Arithmetic},
		"vfnmadd231sd":    {Arithmetic},
		"vpaddd":          {Arithmetic},
		"vpaddq":          {Arithmetic},
		"bsf":             {Transmission},
		"vpcmpeqb":        {Arithmetic},
		"mulss":           {Arithmetic},
		"bsr":             {Transmission},
		"cmova":           {Transmission},
		"cmovae":          {Transmission},
		"cmovb":           {Transmission},
		"cmovbe":          {Transmission},
		"cmove":           {Transmission},
		"cmovg":           {Transmission},
		"cmovge":          {Transmission},
		"cmovl":           {Transmission},
		"cmovle":          {Transmission},
		"cmovne":          {Transmission},
		"lfence":          {Transmission},
		"movabs":          {Transmission},
		"movapd":          {Transmission},
		"movb":            {Transmission},
		"movdqa":          {Transmission},
		"movdqu":          {Transmission},
		"movl":            {Transmission},
		"movq":            {Transmission},
		"movsbq":          {Transmission},
		"movslq":          {Transmission},
		"movss":           {Transmission},
		"movswq":          {Transmission},
		"movups":          {Transmission},
		"movw":            {Transmission},
		"movzbl":          {Transmission},
		"movzwl":          {Transmission},
		"pinsrd":          {Transmission},
		"pinsrq":          {Transmission},
		"pinsrw":          {Transmission},
		"pmovmskb":        {Transmission},
		"popfq":           {Transmission},
		"prefetchnta":     {Transmission},
		"pushfq":          {Transmission},
		"sto":             {Transmission},
		"mfence":          {Transmission},
		"sfence":          {Transmission},
		"vinserti128":     {Transmission},
		"movd":            {Transmission},
		"vmovdqa":         {Transmission},
		"vmovdqu":         {Transmission},
		"vmovntdq":        {Transmission},
		"vpalignr":        {Transmission},
		"vpbroadcastb":    {Transmission},
		"vpshufd":         {Logical},
		"vperm2f128":      {Transmission},
		"vperm2i128":      {Transmission},
		"vpmovmskb":       {Transmission},
		"neg":             {Logical},
		"orpd":            {Logical},
		"orq":             {Logical},
		"pand":            {Logical},
		"pandn":           {Logical},
		"pblendw":         {Logical},
		"pcmpeqb":         {Logical},
		"pcmpeqd":         {Logical},
		"popcnt":          {Logical},
		"punpcklbw":       {Logical},
		"pxor":            {Logical},
		"rex.W":           {Logical},
		"h":               {Logical},
		"rex.WXB":         {Logical},
		"rorx":            {Logical},
		"testb":           {Logical},
		"vpand":           {Logical},
		"vpblendd":        {Logical},
		"vpor":            {Logical},
		"vpshufb":         {Logical},
		"vpslld":          {Logical},
		"vpslldq":         {Logical},
		"vpsllq":          {Logical},
		"vpsrld":          {Logical},
		"vpsrldq":         {Logical},
		"vpsrlq":          {Logical},
		"vptest":          {Logical},
		"vpxor":           {Logical},
		"xorps":           {Logical},
		"callq":           {ProgramTransfer},
		"ja":              {ProgramTransfer},
		"jmpq":            {ProgramTransfer},
		"lret":            {ProgramTransfer},
		"retq":            {ProgramTransfer},
		"syscall":         {ProgramTransfer},
		"cpuid":           {ProcessorControl},
		"nopl":            {ProcessorControl},
		"nopw":            {ProcessorControl},
		"pause":           {ProcessorControl},
		"pshufb":          {ProcessorControl},
		"pshufd":          {ProcessorControl},
		"pshufhw":         {ProcessorControl},
		"rdtsc":           {ProcessorControl},
		"seta":            {ProcessorControl},
		"setae":           {ProcessorControl},
		"setb":            {ProcessorControl},
		"setbe":           {ProcessorControl},
		"sete":            {ProcessorControl},
		"setg":            {ProcessorControl},
		"setge":           {ProcessorControl},
		"setl":            {ProcessorControl},
		"setle":           {ProcessorControl},
		"setne":           {ProcessorControl},
		"setnp":           {ProcessorControl},
		"seto":            {ProcessorControl},
		"setp":            {ProcessorControl},
		"vzeroupper":      {ProcessorControl},
		"xgetbv":          {ProcessorControl},
		"pcmpestri":       {String},
		"int3":            {Interrupt},
		"ud2":             {Interrupt},
		"cvtsd2ss":        {Arithmetic},
		"rdtscp":          {ProcessorControl},
		"prefetcht0":      {Transmission},
		"sha256msg1":      {Arithmetic},
		"sha256msg2":      {Arithmetic},
		"sha256rnds2":     {Arithmetic},
		"aesenc":          {Arithmetic},
		"cvttsd2si":       {Arithmetic},
		"aesdec":          {Arithmetic},
		"aesdeclast":      {Arithmetic},
		"aesenclast":      {Arithmetic},
		"aesimc":          {Arithmetic},
		"aeskeygenassist": {Arithmetic},
		"andl":            {Logical},
		"andnpd":          {Logical},
		"cmpltsd":         {Arithmetic},
		"cvttss2si":       {Transmission},
		"movaps":          {Transmission},
		"orl":             {Logical},
		"pclmulhqhqdq":    {Arithmetic},
		"pclmulhqlqdq":    {Arithmetic},
		"pclmullqhqdq":    {Arithmetic},
		"pclmullqlqdq":    {Arithmetic},
		"pextrb":          {Transmission},
		"pextrd":          {Transmission},
		"pinsrb":          {Transmission},
		"pslld":           {Logical},
		"pslldq":          {Logical},
		"psrad":           {Logical},
		"psrld":           {Logical},
		"psrldq":          {Logical},
		"psrlq":           {Logical},
		"roundsd":         {Arithmetic},
		"shufps":          {ProcessorControl},
		"sqrtsd":          {Arithmetic},
		"vbroadcasti128":  {Transmission},
		"cqo":             {Transmission},
		"leave":           {ProgramTransfer},
		"repnz":           {String},
	}

	X86X64HardwareFeatureInstSet = map[string]TechInstManager{
		"":                  {GP},
		"adc":               {GP},
		"add":               {GP},
		"and":               {GP},
		"bsf":               {GP},
		"bsr":               {GP},
		"bswap":             {GP},
		"bt":                {GP},
		"btc":               {GP},
		"btr":               {GP},
		"bts":               {GP},
		"call":              {GP},
		"cbw":               {GP},
		"cdq":               {GP},
		"cdqe":              {GP},
		"clc":               {GP},
		"cld":               {GP},
		"cmc":               {GP},
		"cmp":               {GP},
		"cmps":              {GP},
		"cwde":              {GP},
		"cqo":               {GP},
		"cwd":               {GP},
		"dec":               {GP},
		"data16":            {GP},
		"div":               {GP},
		"enter":             {GP},
		"idiv":              {GP},
		"imul":              {GP},
		"inc":               {GP},
		"iret":              {GP},
		"iretd":             {GP},
		"iretq":             {GP},
		"jo":                {GP},
		"jno":               {GP},
		"jb":                {GP},
		"jnae":              {GP},
		"jc":                {GP},
		"jae":               {GP},
		"jnb":               {GP},
		"jnc":               {GP},
		"je":                {GP},
		"jz":                {GP},
		"jne":               {GP},
		"jnz":               {GP},
		"jbe":               {GP},
		"jna":               {GP},
		"ja":                {GP},
		"jnbe":              {GP},
		"js":                {GP},
		"jns":               {GP},
		"jp":                {GP},
		"jpe":               {GP},
		"jnp":               {GP},
		"jpo":               {GP},
		"jl":                {GP},
		"jnge":              {GP},
		"jge":               {GP},
		"jnl":               {GP},
		"jle":               {GP},
		"jng":               {GP},
		"jg":                {GP},
		"jnle":              {GP},
		"jecxz":             {GP},
		"jmp":               {GP},
		"lcall":             {GP},
		"lea":               {GP},
		"leave":             {GP},
		"ljmp":              {GP},
		"lods":              {GP},
		"lock":              {GP},
		"loop":              {GP},
		"loope":             {GP},
		"loopne":            {GP},
		"mov":               {GP},
		"movabs":            {GP},
		"movs":              {GP},
		"movsx":             {GP},
		"movsxd":            {GP},
		"movzx":             {GP},
		"mul":               {GP},
		"neg":               {GP},
		"nop":               {GP},
		"not":               {GP},
		"or":                {GP},
		"pop":               {GP},
		"popf":              {GP},
		"popfd":             {GP},
		"popfq":             {GP},
		"push":              {GP},
		"pushf":             {GP},
		"pushfd":            {GP},
		"pushfq":            {GP},
		"rcl":               {GP},
		"rcr":               {GP},
		"ret":               {GP},
		"retf":              {GP},
		"rol":               {GP},
		"ror":               {GP},
		"sar":               {GP},
		"sbb":               {GP},
		"scas":              {GP},
		"seto":              {GP},
		"setno":             {GP},
		"setb":              {GP},
		"setnae":            {GP},
		"setc":              {GP},
		"setae":             {GP},
		"setnb":             {GP},
		"setnc":             {GP},
		"sete":              {GP},
		"setz":              {GP},
		"setne":             {GP},
		"setnz":             {GP},
		"setbe":             {GP},
		"setna":             {GP},
		"seta":              {GP},
		"setnbe":            {GP},
		"sets":              {GP},
		"setns":             {GP},
		"setp":              {GP},
		"setpe":             {GP},
		"setnp":             {GP},
		"setpo":             {GP},
		"setl":              {GP},
		"setnge":            {GP},
		"setge":             {GP},
		"setnl":             {GP},
		"setle":             {GP},
		"setng":             {GP},
		"setg":              {GP},
		"setnle":            {GP},
		"shl":               {GP},
		"sal":               {GP},
		"shr":               {GP},
		"shld":              {GP},
		"shrd":              {GP},
		"stc":               {GP},
		"std":               {GP},
		"stos":              {GP},
		"sub":               {GP},
		"test":              {GP},
		"ud0":               {GP},
		"ud1":               {GP},
		"ud2":               {GP},
		"xchg":              {GP},
		"xor":               {GP},
		"rep":               {GP},
		"repne":             {GP},
		"repe":              {GP},
		"repz":              {GP},
		"repnz":             {GP},
		"in":                {GP, GP_IN_OUT},
		"ins":               {GP, GP_IN_OUT},
		"out":               {GP, GP_IN_OUT},
		"outs":              {GP, GP_IN_OUT},
		"cmpxchg":           {GP, GP_EXT},
		"cpuid":             {GP, GP_EXT},
		"xadd":              {GP, GP_EXT},
		"prefetch":          {GP, GP_EXT},
		"adcx":              {GP, GP_EXT},
		"adox":              {GP, GP_EXT},
		"andn":              {GP, GP_EXT},
		"bextr":             {GP, GP_EXT},
		"blsi":              {GP, GP_EXT},
		"blsmsk":            {GP, GP_EXT},
		"blsr":              {GP, GP_EXT},
		"tzcnt":             {GP, GP_EXT},
		"bzhi":              {GP, GP_EXT},
		"mulx":              {GP, GP_EXT},
		"pdep":              {GP, GP_EXT},
		"pext":              {GP, GP_EXT},
		"rorx":              {GP, GP_EXT},
		"sarx":              {GP, GP_EXT},
		"shlx":              {GP, GP_EXT},
		"shrx":              {GP, GP_EXT},
		"incsspd":           {GP, GP_EXT},
		"incsspq":           {GP, GP_EXT},
		"rdsspd":            {GP, GP_EXT},
		"rdsspq":            {GP, GP_EXT},
		"rstorssp":          {GP, GP_EXT},
		"saveprevssp":       {GP, GP_EXT},
		"cldemote":          {GP, GP_EXT},
		"clflush":           {GP, GP_EXT},
		"clflushopt":        {GP, GP_EXT},
		"clwb":              {GP, GP_EXT},
		"clzero":            {GP, GP_EXT},
		"cmovo":             {GP, GP_EXT},
		"cmovno":            {GP, GP_EXT},
		"cmovb":             {GP, GP_EXT},
		"cmovnae":           {GP, GP_EXT},
		"cmovc":             {GP, GP_EXT},
		"cmovae":            {GP, GP_EXT},
		"cmovnb":            {GP, GP_EXT},
		"cmovnc":            {GP, GP_EXT},
		"cmove":             {GP, GP_EXT},
		"cmovz":             {GP, GP_EXT},
		"cmovne":            {GP, GP_EXT},
		"cmovnz":            {GP, GP_EXT},
		"cmovbe":            {GP, GP_EXT},
		"cmovna":            {GP, GP_EXT},
		"cmova":             {GP, GP_EXT},
		"cmovnbe":           {GP, GP_EXT},
		"cmovs":             {GP, GP_EXT},
		"cmovns":            {GP, GP_EXT},
		"cmovp":             {GP, GP_EXT},
		"cmovpe":            {GP, GP_EXT},
		"cmovnp":            {GP, GP_EXT},
		"cmovpo":            {GP, GP_EXT},
		"cmovl":             {GP, GP_EXT},
		"cmovnge":           {GP, GP_EXT},
		"cmovge":            {GP, GP_EXT},
		"cmovnl":            {GP, GP_EXT},
		"cmovle":            {GP, GP_EXT},
		"cmovng":            {GP, GP_EXT},
		"cmovg":             {GP, GP_EXT},
		"cmovnle":           {GP, GP_EXT},
		"cmpbexadd":         {GP, GP_EXT},
		"cmpbxadd":          {GP, GP_EXT},
		"cmplexadd":         {GP, GP_EXT},
		"cmplxadd":          {GP, GP_EXT},
		"cmpnbexadd":        {GP, GP_EXT},
		"cmpnbxadd":         {GP, GP_EXT},
		"cmpnlexadd":        {GP, GP_EXT},
		"cmpnlxadd":         {GP, GP_EXT},
		"cmpnoxadd":         {GP, GP_EXT},
		"cmpnpxadd":         {GP, GP_EXT},
		"cmpnsxadd":         {GP, GP_EXT},
		"cmpnzxadd":         {GP, GP_EXT},
		"cmpoxadd":          {GP, GP_EXT},
		"cmppxadd":          {GP, GP_EXT},
		"cmpsxadd":          {GP, GP_EXT},
		"cmpzxadd":          {GP, GP_EXT},
		"cmpxchg8b":         {GP, GP_EXT},
		"cmpxchg16b":        {GP, GP_EXT},
		"rdfsbase":          {GP, GP_EXT},
		"rdgsbase":          {GP, GP_EXT},
		"wrfsbase":          {GP, GP_EXT},
		"wrgsbase":          {GP, GP_EXT},
		"fxrstor":           {GP, GP_EXT},
		"fxrstor64":         {GP, GP_EXT},
		"fxsave":            {GP, GP_EXT},
		"fxsave64":          {GP, GP_EXT},
		"lahf":              {GP, GP_EXT},
		"sahf":              {GP, GP_EXT},
		"llwpcb":            {GP, GP_EXT},
		"lwpins":            {GP, GP_EXT},
		"lwpval":            {GP, GP_EXT},
		"slwpcb":            {GP, GP_EXT},
		"lzcnt":             {GP, GP_EXT},
		"monitorx":          {GP, GP_EXT},
		"mwaitx":            {GP, GP_EXT},
		"mcommit":           {GP, GP_EXT},
		"movbe":             {GP, GP_EXT},
		"movdiri":           {GP, GP_EXT},
		"movdir64b":         {GP, GP_EXT},
		"pconfig":           {GP, GP_EXT},
		"popcnt":            {GP, GP_EXT},
		"rdpkru":            {GP, GP_EXT},
		"prefetchit0":       {GP, GP_EXT},
		"prefetchit1":       {GP, GP_EXT},
		"prefetchw":         {GP, GP_EXT},
		"prefetchwt1":       {GP, GP_EXT},
		"ptwrite":           {GP, GP_EXT},
		"aadd":              {GP, GP_EXT},
		"aand":              {GP, GP_EXT},
		"aor":               {GP, GP_EXT},
		"axor":              {GP, GP_EXT},
		"rdpid":             {GP, GP_EXT},
		"rdpru":             {GP, GP_EXT},
		"rdrand":            {GP, GP_EXT},
		"rdseed":            {GP, GP_EXT},
		"rdtsc":             {GP, GP_EXT},
		"rdtscp":            {GP, GP_EXT},
		"xabort":            {GP, GP_EXT},
		"xbegin":            {GP, GP_EXT},
		"xend":              {GP, GP_EXT},
		"serialize":         {GP, GP_EXT},
		"prefetchnta":       {GP, GP_EXT},
		"prefetcht0":        {GP, GP_EXT},
		"prefetcht1":        {GP, GP_EXT},
		"prefetcht2":        {GP, GP_EXT},
		"sfence":            {GP, GP_EXT},
		"lfence":            {GP, GP_EXT},
		"mfence":            {GP, GP_EXT},
		"movnti":            {GP, GP_EXT},
		"crc32":             {GP, GP_EXT, CRYPTO_HASH},
		"pbndkb":            {GP, GP_EXT},
		"xtest":             {GP, GP_EXT},
		"xresldtrk":         {GP, GP_EXT},
		"xsusldtrk":         {GP, GP_EXT},
		"uiret":             {GP, GP_EXT},
		"clui":              {GP, GP_EXT},
		"stui":              {GP, GP_EXT},
		"testui":            {GP, GP_EXT},
		"senduipi":          {GP, GP_EXT},
		"tpause":            {GP, GP_EXT},
		"umonitor":          {GP, GP_EXT},
		"umwait":            {GP, GP_EXT},
		"xgetbv":            {GP, GP_EXT},
		"xrstor":            {GP, GP_EXT},
		"xrstor64":          {GP, GP_EXT},
		"xsave":             {GP, GP_EXT},
		"xsave64":           {GP, GP_EXT},
		"xsavec":            {GP, GP_EXT},
		"xsavec64":          {GP, GP_EXT},
		"xsaveopt":          {GP, GP_EXT},
		"xsaveopt64":        {GP, GP_EXT},
		"cli":               {GP},
		"int":               {GP},
		"int3":              {GP},
		"lar":               {GP},
		"lds":               {GP},
		"les":               {GP},
		"lfs":               {GP},
		"lgs":               {GP},
		"lsl":               {GP},
		"lss":               {GP},
		"pause":             {GP},
		"rsm":               {GP},
		"sgdt":              {GP},
		"sidt":              {GP},
		"sldt":              {GP},
		"smsw":              {GP},
		"sti":               {GP},
		"str":               {GP},
		"syscall":           {GP},
		"sysenter":          {GP},
		"verr":              {GP},
		"verw":              {GP},
		"xlatb":             {GP},
		"aaa":               {GP},
		"aas":               {GP},
		"aad":               {GP},
		"aam":               {GP},
		"arpl":              {GP},
		"bound":             {GP},
		"daa":               {GP},
		"das":               {GP},
		"into":              {GP},
		"popa":              {GP},
		"popad":             {GP},
		"pusha":             {GP},
		"pushad":            {GP},
		"bndcl":             {GP, GP_EXT},
		"bndcn":             {GP, GP_EXT},
		"bndcu":             {GP, GP_EXT},
		"bndldx":            {GP, GP_EXT},
		"bndmk":             {GP, GP_EXT},
		"bndmov":            {GP, GP_EXT},
		"bndstx":            {GP, GP_EXT},
		"blci":              {GP, GP_EXT},
		"blcic":             {GP, GP_EXT},
		"blsic":             {GP, GP_EXT},
		"blcfill":           {GP, GP_EXT},
		"blsfill":           {GP, GP_EXT},
		"blcmsk":            {GP, GP_EXT},
		"blcs":              {GP, GP_EXT},
		"tzmsk":             {GP, GP_EXT},
		"t1mskc":            {GP, GP_EXT},
		"clts":              {GP},
		"hlt":               {GP},
		"lgdt":              {GP},
		"lidt":              {GP},
		"lldt":              {GP},
		"lmsw":              {GP},
		"ltr":               {GP},
		"rdpmc":             {GP},
		"swapgs":            {GP},
		"sysexit":           {GP},
		"sysexitq":          {GP},
		"sysret":            {GP},
		"sysretq":           {GP},
		"invd":              {GP},
		"invlpg":            {GP},
		"invpcid":           {GP},
		"wbinvd":            {GP},
		"endbr32":           {GP, GP_EXT},
		"endbr64":           {GP, GP_EXT},
		"clrssbsy":          {GP, GP_EXT},
		"setssbsy":          {GP, GP_EXT},
		"wrssd":             {GP, GP_EXT},
		"wrssq":             {GP, GP_EXT},
		"wrussd":            {GP, GP_EXT},
		"wrussq":            {GP, GP_EXT},
		"hreset":            {GP, GP_EXT},
		"monitor":           {GP, GP_EXT},
		"mwait":             {GP, GP_EXT},
		"rdmsr":             {GP, GP_EXT},
		"wrmsr":             {GP, GP_EXT},
		"rdmsrlist":         {GP, GP_EXT},
		"wrmsrlist":         {GP, GP_EXT},
		"getsec":            {GP, GP_EXT},
		"wbnoinvd":          {GP, GP_EXT},
		"wrmsrns":           {GP, GP_EXT},
		"xsetbv":            {GP, GP_EXT},
		"xrstors":           {GP, GP_EXT},
		"xrstors64":         {GP, GP_EXT},
		"xsaves":            {GP, GP_EXT},
		"xsaves64":          {GP, GP_EXT},
		"clac":              {VIRTUALIZATION},
		"stac":              {VIRTUALIZATION},
		"enqcmd":            {VIRTUALIZATION},
		"enqcmds":           {VIRTUALIZATION},
		"invept":            {VIRTUALIZATION},
		"invvpid":           {VIRTUALIZATION},
		"seamcall":          {VIRTUALIZATION},
		"seamops":           {VIRTUALIZATION},
		"seamret":           {VIRTUALIZATION},
		"tdcall":            {VIRTUALIZATION},
		"vmcall":            {VIRTUALIZATION},
		"vmclear":           {VIRTUALIZATION},
		"vmfunc":            {VIRTUALIZATION},
		"vmlaunch":          {VIRTUALIZATION},
		"vmptrld":           {VIRTUALIZATION},
		"vmptrst":           {VIRTUALIZATION},
		"vmread":            {VIRTUALIZATION},
		"vmresume":          {VIRTUALIZATION},
		"vmwrite":           {VIRTUALIZATION},
		"vmxoff":            {VIRTUALIZATION},
		"vmxon":             {VIRTUALIZATION},
		"vmmcall":           {VIRTUALIZATION},
		"clgi":              {VIRTUALIZATION},
		"invlpga":           {VIRTUALIZATION},
		"invlpgb":           {VIRTUALIZATION},
		"psmash":            {VIRTUALIZATION},
		"pvalidate":         {VIRTUALIZATION},
		"rmpadjust":         {VIRTUALIZATION},
		"rmpquery":          {VIRTUALIZATION},
		"rmpupdate":         {VIRTUALIZATION},
		"skinit":            {VIRTUALIZATION},
		"stgi":              {VIRTUALIZATION},
		"tlbsync":           {VIRTUALIZATION},
		"vmgexit":           {VIRTUALIZATION},
		"vmload":            {VIRTUALIZATION},
		"vmrun":             {VIRTUALIZATION},
		"vmsave":            {VIRTUALIZATION},
		"f2xm1":             {FPU},
		"fabs":              {FPU},
		"fadd":              {FPU},
		"faddp":             {FPU},
		"fbld":              {FPU},
		"fbstp":             {FPU},
		"fchs":              {FPU},
		"fclex":             {FPU},
		"fcom":              {FPU},
		"fcomi":             {FPU},
		"fcomip":            {FPU},
		"fcomp":             {FPU},
		"fcompp":            {FPU},
		"fcos":              {FPU},
		"fdecstp":           {FPU},
		"fdiv":              {FPU},
		"fdivp":             {FPU},
		"fdivr":             {FPU},
		"fdivrp":            {FPU},
		"ffree":             {FPU},
		"fiadd":             {FPU},
		"ficom":             {FPU},
		"ficomp":            {FPU},
		"fidiv":             {FPU},
		"fidivr":            {FPU},
		"fild":              {FPU},
		"fimul":             {FPU},
		"fincstp":           {FPU},
		"finit":             {FPU},
		"fist":              {FPU},
		"fistp":             {FPU},
		"fisub":             {FPU},
		"fisubr":            {FPU},
		"fld":               {FPU},
		"fld1":              {FPU},
		"fldcw":             {FPU},
		"fldenv":            {FPU},
		"fldl2e":            {FPU},
		"fldl2t":            {FPU},
		"fldlg2":            {FPU},
		"fldln2":            {FPU},
		"fldpi":             {FPU},
		"fldz":              {FPU},
		"fmul":              {FPU},
		"fmulp":             {FPU},
		"fnclex":            {FPU},
		"fninit":            {FPU},
		"fnop":              {FPU},
		"fnsave":            {FPU},
		"fnstcw":            {FPU},
		"fnstenv":           {FPU},
		"fnstsw":            {FPU},
		"fpatan":            {FPU},
		"fprem":             {FPU},
		"fprem1":            {FPU},
		"fptan":             {FPU},
		"frndint":           {FPU},
		"frstor":            {FPU},
		"fsave":             {FPU},
		"fscale":            {FPU},
		"fsin":              {FPU},
		"fsincos":           {FPU},
		"fsqrt":             {FPU},
		"fst":               {FPU},
		"fstcw":             {FPU},
		"fstenv":            {FPU},
		"fstp":              {FPU},
		"fstsw":             {FPU},
		"fsub":              {FPU},
		"fsubp":             {FPU},
		"fsubr":             {FPU},
		"fsubrp":            {FPU},
		"ftst":              {FPU},
		"fucom":             {FPU},
		"fucomi":            {FPU},
		"fucomip":           {FPU},
		"fucomp":            {FPU},
		"fucompp":           {FPU},
		"fwait":             {FPU},
		"wait":              {FPU},
		"fxam":              {FPU},
		"fxch":              {FPU},
		"fxtract":           {FPU},
		"fyl2x":             {FPU},
		"fyl2xp1":           {FPU},
		"fcmovb":            {FPU},
		"fcmovbe":           {FPU},
		"fcmove":            {FPU},
		"fcmovnb":           {FPU},
		"fcmovnbe":          {FPU},
		"fcmovne":           {FPU},
		"fcmovnu":           {FPU},
		"fcmovu":            {FPU},
		"fisttp":            {FPU},
		"emms":              {MMX, STATE},
		"femms":             {MMX, STATE},
		"movd":              {MMX, SIMD},
		"movq":              {MMX, SIMD},
		"packssdw":          {MMX, SIMD},
		"packsswb":          {MMX, SIMD},
		"packuswb":          {MMX, SIMD},
		"paddb":             {MMX, SIMD},
		"paddd":             {MMX, SIMD},
		"paddsb":            {MMX, SIMD},
		"paddsw":            {MMX, SIMD},
		"paddusb":           {MMX, SIMD},
		"paddusw":           {MMX, SIMD},
		"paddw":             {MMX, SIMD},
		"pand":              {MMX, SIMD},
		"pandn":             {MMX, SIMD},
		"pcmpeqb":           {MMX, SIMD},
		"pcmpeqd":           {MMX, SIMD},
		"pcmpeqw":           {MMX, SIMD},
		"pcmpgtb":           {MMX, SIMD},
		"pcmpgtd":           {MMX, SIMD},
		"pcmpgtw":           {MMX, SIMD},
		"pmaddwd":           {MMX, SIMD},
		"pmulhw":            {MMX, SIMD},
		"pmullw":            {MMX, SIMD},
		"por":               {MMX, SIMD},
		"pslld":             {MMX, SIMD},
		"psllq":             {MMX, SIMD},
		"psllw":             {MMX, SIMD},
		"psrad":             {MMX, SIMD},
		"psraw":             {MMX, SIMD},
		"psrld":             {MMX, SIMD},
		"psrlq":             {MMX, SIMD},
		"psrlw":             {MMX, SIMD},
		"psubb":             {MMX, SIMD},
		"psubd":             {MMX, SIMD},
		"psubsb":            {MMX, SIMD},
		"psubsw":            {MMX, SIMD},
		"psubusb":           {MMX, SIMD},
		"psubusw":           {MMX, SIMD},
		"psubw":             {MMX, SIMD},
		"punpckhbw":         {MMX, SIMD},
		"punpckhdq":         {MMX, SIMD},
		"punpckhwd":         {MMX, SIMD},
		"punpcklbw":         {MMX, SIMD},
		"punpckldq":         {MMX, SIMD},
		"punpcklwd":         {MMX, SIMD},
		"pxor":              {MMX, SIMD},
		"maskmovq":          {MMX, SIMD},
		"movntq":            {MMX, SIMD},
		"pavgb":             {MMX, SIMD},
		"pavgw":             {MMX, SIMD},
		"pextrw":            {MMX, SIMD},
		"pinsrw":            {MMX, SIMD},
		"pmaxsw":            {MMX, SIMD},
		"pmaxub":            {MMX, SIMD},
		"pminsw":            {MMX, SIMD},
		"pminub":            {MMX, SIMD},
		"pmovmskb":          {MMX, SIMD},
		"pmulhuw":           {MMX, SIMD},
		"psadbw":            {MMX, SIMD},
		"pshufw":            {MMX, SIMD},
		"pavgusb":           {MMX, SIMD},
		"pf2id":             {MMX, SIMD},
		"pfacc":             {MMX, SIMD},
		"pfadd":             {MMX, SIMD},
		"pfcmpeq":           {MMX, SIMD},
		"pfcmpge":           {MMX, SIMD},
		"pfcmpgt":           {MMX, SIMD},
		"pfmax":             {MMX, SIMD},
		"pfmin":             {MMX, SIMD},
		"pfmul":             {MMX, SIMD},
		"pfrcp":             {MMX, SIMD},
		"pfrcpit1":          {MMX, SIMD},
		"pfrcpit2":          {MMX, SIMD},
		"pfrsqit1":          {MMX, SIMD},
		"pfrsqrt":           {MMX, SIMD},
		"pfsub":             {MMX, SIMD},
		"pfsubr":            {MMX, SIMD},
		"pi2fd":             {MMX, SIMD},
		"pmulhrw":           {MMX, SIMD},
		"pf2iw":             {MMX, SIMD},
		"pfnacc":            {MMX, SIMD},
		"pfpnacc":           {MMX, SIMD},
		"pi2fw":             {MMX, SIMD},
		"pswapd":            {MMX, SIMD},
		"pfrcpv":            {MMX, SIMD},
		"pfrsqrtv":          {MMX, SIMD},
		"ldmxcsr":           {SSE, STATE},
		"stmxcsr":           {SSE, STATE},
		"addss":             {SSE, SCALAR},
		"cmpss":             {SSE, SCALAR},
		"comiss":            {SSE, SCALAR},
		"cvtsi2ss":          {SSE, SCALAR},
		"cvtss2si":          {SSE, SCALAR},
		"cvttss2si":         {SSE, SCALAR},
		"divss":             {SSE, SCALAR},
		"maxss":             {SSE, SCALAR},
		"minss":             {SSE, SCALAR},
		"movss":             {SSE, SCALAR},
		"mulss":             {SSE, SCALAR},
		"rcpss":             {SSE, SCALAR},
		"rsqrtss":           {SSE, SCALAR},
		"sqrtss":            {SSE, SCALAR},
		"subss":             {SSE, SCALAR},
		"ucomiss":           {SSE, SCALAR},
		"addps":             {SSE, SIMD},
		"andnps":            {SSE, SIMD},
		"andps":             {SSE, SIMD},
		"cmpps":             {SSE, SIMD},
		"cvtpi2ps":          {SSE, SIMD},
		"cvtps2pi":          {SSE, SIMD},
		"cvttps2pi":         {SSE, SIMD},
		"divps":             {SSE, SIMD},
		"maxps":             {SSE, SIMD},
		"minps":             {SSE, SIMD},
		"movaps":            {SSE, SIMD},
		"movhlps":           {SSE, SIMD},
		"movhps":            {SSE, SIMD},
		"movlhps":           {SSE, SIMD},
		"movlps":            {SSE, SIMD},
		"movmskps":          {SSE, SIMD},
		"movntps":           {SSE, SIMD},
		"movups":            {SSE, SIMD},
		"mulps":             {SSE, SIMD},
		"orps":              {SSE, SIMD},
		"rcpps":             {SSE, SIMD},
		"rsqrtps":           {SSE, SIMD},
		"shufps":            {SSE, SIMD},
		"sqrtps":            {SSE, SIMD},
		"subps":             {SSE, SIMD},
		"unpckhps":          {SSE, SIMD},
		"unpcklps":          {SSE, SIMD},
		"xorps":             {SSE, SIMD},
		"addsd":             {SSE, SCALAR},
		"cmpsd":             {SSE, SCALAR},
		"comisd":            {SSE, SCALAR},
		"cvtsd2si":          {SSE, SCALAR},
		"cvtsd2ss":          {SSE, SCALAR},
		"cvtsi2sd":          {SSE, SCALAR},
		"cvtss2sd":          {SSE, SCALAR},
		"cvttsd2si":         {SSE, SCALAR},
		"divsd":             {SSE, SCALAR},
		"maxsd":             {SSE, SCALAR},
		"minsd":             {SSE, SCALAR},
		"movsd":             {SSE, SCALAR},
		"mulsd":             {SSE, SCALAR},
		"sqrtsd":            {SSE, SCALAR},
		"subsd":             {SSE, SCALAR},
		"ucomisd":           {SSE, SCALAR},
		"addpd":             {SSE, SIMD},
		"andnpd":            {SSE, SIMD},
		"andpd":             {SSE, SIMD},
		"cmppd":             {SSE, SIMD},
		"cvtdq2pd":          {SSE, SIMD},
		"cmpltps":           {SSE, SIMD},
		"cmpeqps":           {SSE, SIMD},
		"cvtdq2ps":          {SSE, SIMD},
		"cvtpd2dq":          {SSE, SIMD},
		"cvtpd2pi":          {SSE, SIMD},
		"cvtpd2ps":          {SSE, SIMD},
		"cvtpi2pd":          {SSE, SIMD},
		"cvtps2dq":          {SSE, SIMD},
		"cvtps2pd":          {SSE, SIMD},
		"cvttpd2dq":         {SSE, SIMD},
		"cvttpd2pi":         {SSE, SIMD},
		"cvttps2dq":         {SSE, SIMD},
		"divpd":             {SSE, SIMD},
		"maskmovdqu":        {SSE, SIMD},
		"maxpd":             {SSE, SIMD},
		"minpd":             {SSE, SIMD},
		"movapd":            {SSE, SIMD},
		"movdq2q":           {SSE, SIMD},
		"movdqa":            {SSE, SIMD},
		"movdqu":            {SSE, SIMD},
		"cmpltpd":           {SSE, SIMD},
		"cmplepd":           {SSE, SIMD},
		"cmplesd":           {SSE, SIMD},
		"movhpd":            {SSE, SIMD},
		"movlpd":            {SSE, SIMD},
		"movmskpd":          {SSE, SIMD},
		"movntdq":           {SSE, SIMD},
		"cmpltsd":           {SSE, SIMD},
		"cmpltss":           {SSE, SIMD},
		"cmpnltss":          {SSE, SIMD},
		"cmpnltsd":          {SSE, SIMD},
		"movntpd":           {SSE, SIMD},
		"movq2dq":           {SSE, SIMD},
		"movupd":            {SSE, SIMD},
		"mulpd":             {SSE, SIMD},
		"orpd":              {SSE, SIMD},
		"paddq":             {SSE, SIMD},
		"pmuludq":           {SSE, SIMD},
		"pshufd":            {SSE, SIMD},
		"pshufhw":           {SSE, SIMD},
		"pshuflw":           {SSE, SIMD},
		"pslldq":            {SSE, SIMD},
		"psrldq":            {SSE, SIMD},
		"psubq":             {SSE, SIMD},
		"punpckhqdq":        {SSE, SIMD},
		"punpcklqdq":        {SSE, SIMD},
		"shufpd":            {SSE, SIMD},
		"sqrtpd":            {SSE, SIMD},
		"subpd":             {SSE, SIMD},
		"unpckhpd":          {SSE, SIMD},
		"unpcklpd":          {SSE, SIMD},
		"xorpd":             {SSE, SIMD},
		"addsubpd":          {SSE, SIMD},
		"addsubps":          {SSE, SIMD},
		"haddpd":            {SSE, SIMD},
		"haddps":            {SSE, SIMD},
		"hsubpd":            {SSE, SIMD},
		"hsubps":            {SSE, SIMD},
		"lddqu":             {SSE, SIMD},
		"movddup":           {SSE, SIMD},
		"movshdup":          {SSE, SIMD},
		"movsldup":          {SSE, SIMD},
		"pabsb":             {SSE, SIMD},
		"pabsd":             {SSE, SIMD},
		"pabsw":             {SSE, SIMD},
		"palignr":           {SSE, SIMD},
		"phaddd":            {SSE, SIMD},
		"phaddsw":           {SSE, SIMD},
		"phaddw":            {SSE, SIMD},
		"phsubd":            {SSE, SIMD},
		"phsubsw":           {SSE, SIMD},
		"phsubw":            {SSE, SIMD},
		"pmaddubsw":         {SSE, SIMD},
		"pmulhrsw":          {SSE, SIMD},
		"pshufb":            {SSE, SIMD},
		"psignb":            {SSE, SIMD},
		"psignd":            {SSE, SIMD},
		"psignw":            {SSE, SIMD},
		"roundsd":           {SSE, SCALAR},
		"roundss":           {SSE, SCALAR},
		"blendpd":           {SSE, SIMD},
		"blendps":           {SSE, SIMD},
		"blendvpd":          {SSE, SIMD},
		"blendvps":          {SSE, SIMD},
		"dppd":              {SSE, SIMD},
		"dpps":              {SSE, SIMD},
		"extractps":         {SSE, SIMD},
		"insertps":          {SSE, SIMD},
		"movntdqa":          {SSE, SIMD},
		"mpsadbw":           {SSE, SIMD},
		"packusdw":          {SSE, SIMD},
		"pblendvb":          {SSE, SIMD},
		"pblendw":           {SSE, SIMD},
		"pcmpeqq":           {SSE, SIMD},
		"pextrb":            {SSE, SIMD},
		"pextrd":            {SSE, SIMD},
		"pextrq":            {SSE, SIMD},
		"phminposuw":        {SSE, SIMD},
		"pinsrb":            {SSE, SIMD},
		"pinsrd":            {SSE, SIMD},
		"pinsrq":            {SSE, SIMD},
		"pmaxsb":            {SSE, SIMD},
		"pmaxsd":            {SSE, SIMD},
		"pmaxud":            {SSE, SIMD},
		"pmaxuw":            {SSE, SIMD},
		"pminsb":            {SSE, SIMD},
		"pminsd":            {SSE, SIMD},
		"pminud":            {SSE, SIMD},
		"pminuw":            {SSE, SIMD},
		"pmovsxbd":          {SSE, SIMD},
		"pmovsxbq":          {SSE, SIMD},
		"pmovsxbw":          {SSE, SIMD},
		"pmovsxdq":          {SSE, SIMD},
		"pmovsxwd":          {SSE, SIMD},
		"pmovsxwq":          {SSE, SIMD},
		"pmovzxbd":          {SSE, SIMD},
		"pmovzxbq":          {SSE, SIMD},
		"pmovzxbw":          {SSE, SIMD},
		"pmovzxdq":          {SSE, SIMD},
		"pmovzxwd":          {SSE, SIMD},
		"pmovzxwq":          {SSE, SIMD},
		"pmuldq":            {SSE, SIMD},
		"pmulld":            {SSE, SIMD},
		"ptest":             {SSE, SIMD},
		"roundpd":           {SSE, SIMD},
		"roundps":           {SSE, SIMD},
		"pcmpestri":         {SSE, SIMD},
		"pcmpestrm":         {SSE, SIMD},
		"pcmpgtq":           {SSE, SIMD},
		"pcmpistri":         {SSE, SIMD},
		"pcmpistrm":         {SSE, SIMD},
		"movntsd":           {SSE, SCALAR},
		"movntss":           {SSE, SCALAR},
		"extrq":             {SSE, SIMD},
		"insertq":           {SSE, SIMD},
		"aesdec":            {SSE, SIMD, CRYPTO_HASH},
		"aesdeclast":        {SSE, SIMD, CRYPTO_HASH},
		"aesenc":            {SSE, SIMD, CRYPTO_HASH},
		"aesenclast":        {SSE, SIMD, CRYPTO_HASH},
		"aesimc":            {SSE, SIMD, CRYPTO_HASH},
		"aeskeygenassist":   {SSE, SIMD, CRYPTO_HASH},
		"gf2p8affineinvqb":  {SSE, SIMD},
		"gf2p8affineqb":     {SSE, SIMD},
		"gf2p8mulb":         {SSE, SIMD},
		"pclmulqdq":         {SSE, SIMD},
		"sha1msg1":          {SSE, SIMD, CRYPTO_HASH},
		"sha1msg2":          {SSE, SIMD, CRYPTO_HASH},
		"sha1nexte":         {SSE, SIMD, CRYPTO_HASH},
		"sha1rnds4":         {SSE, SIMD, CRYPTO_HASH},
		"sha256msg1":        {SSE, SIMD, CRYPTO_HASH},
		"sha256msg2":        {SSE, SIMD, CRYPTO_HASH},
		"sha256rnds2":       {SSE, SIMD, CRYPTO_HASH},
		"vldmxcsr":          {AVX, STATE},
		"vstmxcsr":          {AVX, STATE},
		"vzeroall":          {AVX, STATE},
		"vzeroupper":        {AVX, STATE},
		"vaddsd":            {AVX, SCALAR},
		"vaddss":            {AVX, SCALAR},
		"vcmpsd":            {AVX, SCALAR},
		"vcmpss":            {AVX, SCALAR},
		"vcomisd":           {AVX, SCALAR},
		"vcomiss":           {AVX, SCALAR},
		"vcvtsd2si":         {AVX, SCALAR},
		"vcvtsd2ss":         {AVX, SCALAR},
		"vcvtsi2sd":         {AVX, SCALAR},
		"vcvtsi2ss":         {AVX, SCALAR},
		"vcvtss2sd":         {AVX, SCALAR},
		"vcvtss2si":         {AVX, SCALAR},
		"vcvttsd2si":        {AVX, SCALAR},
		"vcvttss2si":        {AVX, SCALAR},
		"vdivsd":            {AVX, SCALAR},
		"vdivss":            {AVX, SCALAR},
		"vmaxsd":            {AVX, SCALAR},
		"vmaxss":            {AVX, SCALAR},
		"vminsd":            {AVX, SCALAR},
		"vminss":            {AVX, SCALAR},
		"vmovsd":            {AVX, SCALAR},
		"vmovss":            {AVX, SCALAR},
		"vmulsd":            {AVX, SCALAR},
		"vmulss":            {AVX, SCALAR},
		"vrcpss":            {AVX, SCALAR},
		"vroundsd":          {AVX, SCALAR},
		"vroundss":          {AVX, SCALAR},
		"vrsqrtss":          {AVX, SCALAR},
		"vsqrtsd":           {AVX, SCALAR},
		"vsqrtss":           {AVX, SCALAR},
		"vsubsd":            {AVX, SCALAR},
		"vsubss":            {AVX, SCALAR},
		"vucomisd":          {AVX, SCALAR},
		"vucomiss":          {AVX, SCALAR},
		"vaddpd":            {AVX, SIMD},
		"vaddps":            {AVX, SIMD},
		"vaddsubpd":         {AVX, SIMD},
		"vaddsubps":         {AVX, SIMD},
		"vandnpd":           {AVX, SIMD},
		"vandnps":           {AVX, SIMD},
		"vandpd":            {AVX, SIMD},
		"vandps":            {AVX, SIMD},
		"vblendpd":          {AVX, SIMD},
		"vblendps":          {AVX, SIMD},
		"vblendvpd":         {AVX, SIMD},
		"vblendvps":         {AVX, SIMD},
		"vbroadcastf128":    {AVX, SIMD},
		"vbroadcastsd":      {AVX, SIMD},
		"vbroadcastss":      {AVX, SIMD},
		"vcmppd":            {AVX, SIMD},
		"vcmpps":            {AVX, SIMD},
		"vcvtdq2pd":         {AVX, SIMD},
		"vcvtdq2ps":         {AVX, SIMD},
		"vcvtpd2dq":         {AVX, SIMD},
		"vcvtpd2ps":         {AVX, SIMD},
		"vcvtps2dq":         {AVX, SIMD},
		"vcvtps2pd":         {AVX, SIMD},
		"vcvttpd2dq":        {AVX, SIMD},
		"vcvttps2dq":        {AVX, SIMD},
		"vdivpd":            {AVX, SIMD},
		"vdivps":            {AVX, SIMD},
		"vdppd":             {AVX, SIMD},
		"vdpps":             {AVX, SIMD},
		"vextractps":        {AVX, SIMD},
		"vextractf128":      {AVX, SIMD},
		"vhaddpd":           {AVX, SIMD},
		"vhaddps":           {AVX, SIMD},
		"vhsubpd":           {AVX, SIMD},
		"vhsubps":           {AVX, SIMD},
		"vinsertf128":       {AVX, SIMD},
		"vinsertps":         {AVX, SIMD},
		"vlddqu":            {AVX, SIMD},
		"vmaskmovdqu":       {AVX, SIMD},
		"vmaskmovpd":        {AVX, SIMD},
		"vmaskmovps":        {AVX, SIMD},
		"vmaxpd":            {AVX, SIMD},
		"vmaxps":            {AVX, SIMD},
		"vminpd":            {AVX, SIMD},
		"vminps":            {AVX, SIMD},
		"vmovapd":           {AVX, SIMD},
		"vmovaps":           {AVX, SIMD},
		"vmovd":             {AVX, SIMD},
		"vmovddup":          {AVX, SIMD},
		"vmovdqa":           {AVX, SIMD},
		"vmovdqu":           {AVX, SIMD},
		"vmovhlps":          {AVX, SIMD},
		"vmovhpd":           {AVX, SIMD},
		"vmovhps":           {AVX, SIMD},
		"vmovlhps":          {AVX, SIMD},
		"vmovlpd":           {AVX, SIMD},
		"vmovlps":           {AVX, SIMD},
		"vmovmskpd":         {AVX, SIMD},
		"vmovmskps":         {AVX, SIMD},
		"vmovntdq":          {AVX, SIMD},
		"vmovntdqa":         {AVX, SIMD},
		"vmovntpd":          {AVX, SIMD},
		"vmovntps":          {AVX, SIMD},
		"vmovq":             {AVX, SIMD},
		"vmovshdup":         {AVX, SIMD},
		"vmovsldup":         {AVX, SIMD},
		"vmovupd":           {AVX, SIMD},
		"vmovups":           {AVX, SIMD},
		"vmpsadbw":          {AVX, SIMD},
		"vmulpd":            {AVX, SIMD},
		"vmulps":            {AVX, SIMD},
		"vorpd":             {AVX, SIMD},
		"vorps":             {AVX, SIMD},
		"vpabsb":            {AVX, SIMD},
		"vpabsd":            {AVX, SIMD},
		"vpabsw":            {AVX, SIMD},
		"vpackssdw":         {AVX, SIMD},
		"vpacksswb":         {AVX, SIMD},
		"vpackusdw":         {AVX, SIMD},
		"vpackuswb":         {AVX, SIMD},
		"vpaddb":            {AVX, SIMD},
		"vpaddd":            {AVX, SIMD},
		"vpaddq":            {AVX, SIMD},
		"vpaddsb":           {AVX, SIMD},
		"vpaddsw":           {AVX, SIMD},
		"vpaddusb":          {AVX, SIMD},
		"vpaddusw":          {AVX, SIMD},
		"vpaddw":            {AVX, SIMD},
		"vpalignr":          {AVX, SIMD},
		"vpand":             {AVX, SIMD},
		"vpandn":            {AVX, SIMD},
		"vpavgb":            {AVX, SIMD},
		"vpavgw":            {AVX, SIMD},
		"vpblendvb":         {AVX, SIMD},
		"vpblendw":          {AVX, SIMD},
		"vpcmpeqb":          {AVX, SIMD},
		"vpcmpeqd":          {AVX, SIMD},
		"vpcmpeqq":          {AVX, SIMD},
		"vpcmpeqw":          {AVX, SIMD},
		"vpcmpestri":        {AVX, SIMD},
		"vpcmpestrm":        {AVX, SIMD},
		"vpcmpgtb":          {AVX, SIMD},
		"vpcmpgtd":          {AVX, SIMD},
		"vpcmpgtq":          {AVX, SIMD},
		"vpcmpgtw":          {AVX, SIMD},
		"vpcmpistri":        {AVX, SIMD},
		"vpcmpistrm":        {AVX, SIMD},
		"vperm2f128":        {AVX, SIMD},
		"vpermilpd":         {AVX, SIMD},
		"vpermilps":         {AVX, SIMD},
		"vpextrb":           {AVX, SIMD},
		"vpextrd":           {AVX, SIMD},
		"vpextrq":           {AVX, SIMD},
		"vpextrw":           {AVX, SIMD},
		"vphaddd":           {AVX, SIMD},
		"vphaddsw":          {AVX, SIMD},
		"vphaddw":           {AVX, SIMD},
		"vphminposuw":       {AVX, SIMD},
		"vphsubd":           {AVX, SIMD},
		"vphsubsw":          {AVX, SIMD},
		"vphsubw":           {AVX, SIMD},
		"vpinsrb":           {AVX, SIMD},
		"vpinsrd":           {AVX, SIMD},
		"vpinsrq":           {AVX, SIMD},
		"vpinsrw":           {AVX, SIMD},
		"vpmaddubsw":        {AVX, SIMD},
		"vpmaddwd":          {AVX, SIMD},
		"vpmaxsb":           {AVX, SIMD},
		"vpmaxsd":           {AVX, SIMD},
		"vpmaxsw":           {AVX, SIMD},
		"vpmaxub":           {AVX, SIMD},
		"vpmaxud":           {AVX, SIMD},
		"vpmaxuw":           {AVX, SIMD},
		"vpminsb":           {AVX, SIMD},
		"vpminsd":           {AVX, SIMD},
		"vpminsw":           {AVX, SIMD},
		"vpminub":           {AVX, SIMD},
		"vpminud":           {AVX, SIMD},
		"vpminuw":           {AVX, SIMD},
		"vpmovmskb":         {AVX, SIMD},
		"vpmovsxwq":         {AVX, SIMD},
		"vpmovsxbd":         {AVX, SIMD},
		"vpmovsxbq":         {AVX, SIMD},
		"vpmovsxbw":         {AVX, SIMD},
		"vpmovsxdq":         {AVX, SIMD},
		"vpmovsxwd":         {AVX, SIMD},
		"vpmovzxbd":         {AVX, SIMD},
		"vpmovzxbq":         {AVX, SIMD},
		"vpmovzxbw":         {AVX, SIMD},
		"vpmovzxdq":         {AVX, SIMD},
		"vpmovzxwd":         {AVX, SIMD},
		"vpmovzxwq":         {AVX, SIMD},
		"vpmuldq":           {AVX, SIMD},
		"vpmulhrsw":         {AVX, SIMD},
		"vpmulhuw":          {AVX, SIMD},
		"vpmulhw":           {AVX, SIMD},
		"vpmulld":           {AVX, SIMD},
		"vpmullw":           {AVX, SIMD},
		"vpmuludq":          {AVX, SIMD},
		"vpor":              {AVX, SIMD},
		"vpsadbw":           {AVX, SIMD},
		"vpshufb":           {AVX, SIMD},
		"vpshufd":           {AVX, SIMD},
		"vpshufhw":          {AVX, SIMD},
		"vpshuflw":          {AVX, SIMD},
		"vpsignb":           {AVX, SIMD},
		"vpsignd":           {AVX, SIMD},
		"vpsignw":           {AVX, SIMD},
		"vpslld":            {AVX, SIMD},
		"vpslldq":           {AVX, SIMD},
		"vpsllq":            {AVX, SIMD},
		"vpsllw":            {AVX, SIMD},
		"vpsrad":            {AVX, SIMD},
		"vpsraw":            {AVX, SIMD},
		"vpsrld":            {AVX, SIMD},
		"vpsrldq":           {AVX, SIMD},
		"vpsrlq":            {AVX, SIMD},
		"vpsrlw":            {AVX, SIMD},
		"vpsubb":            {AVX, SIMD},
		"vpsubd":            {AVX, SIMD},
		"vpsubq":            {AVX, SIMD},
		"vpsubsb":           {AVX, SIMD},
		"vpsubsw":           {AVX, SIMD},
		"vpsubusb":          {AVX, SIMD},
		"vpsubusw":          {AVX, SIMD},
		"vpsubw":            {AVX, SIMD},
		"vptest":            {AVX, SIMD},
		"vpunpckhbw":        {AVX, SIMD},
		"vpunpckhdq":        {AVX, SIMD},
		"vpunpckhqdq":       {AVX, SIMD},
		"vpunpckhwd":        {AVX, SIMD},
		"vpunpcklbw":        {AVX, SIMD},
		"vpunpckldq":        {AVX, SIMD},
		"vpunpcklqdq":       {AVX, SIMD},
		"vpunpcklwd":        {AVX, SIMD},
		"vpxor":             {AVX, SIMD},
		"vrcpps":            {AVX, SIMD},
		"vroundpd":          {AVX, SIMD},
		"vroundps":          {AVX, SIMD},
		"vrsqrtps":          {AVX, SIMD},
		"vshufpd":           {AVX, SIMD},
		"vshufps":           {AVX, SIMD},
		"vsqrtpd":           {AVX, SIMD},
		"vsqrtps":           {AVX, SIMD},
		"vsubpd":            {AVX, SIMD},
		"vsubps":            {AVX, SIMD},
		"vtestpd":           {AVX, SIMD},
		"vtestps":           {AVX, SIMD},
		"vunpckhpd":         {AVX, SIMD},
		"vunpckhps":         {AVX, SIMD},
		"vunpcklpd":         {AVX, SIMD},
		"vunpcklps":         {AVX, SIMD},
		"vxorpd":            {AVX, SIMD},
		"vxorps":            {AVX, SIMD},
		"vaesdec":           {AVX, SIMD, CRYPTO_HASH},
		"vaesdeclast":       {AVX, SIMD, CRYPTO_HASH},
		"vaesenc":           {AVX, SIMD, CRYPTO_HASH},
		"vaesenclast":       {AVX, SIMD, CRYPTO_HASH},
		"vaesimc":           {AVX, SIMD, CRYPTO_HASH},
		"vaeskeygenassist":  {AVX, SIMD, CRYPTO_HASH},
		"vgf2p8affineinvqb": {AVX, SIMD},
		"vgf2p8affineqb":    {AVX, SIMD},
		"vgf2p8mulb":        {AVX, SIMD},
		"vpclmulqdq":        {AVX, SIMD},
		"vbroadcasti128":    {AVX, SIMD},
		"vextracti128":      {AVX, SIMD},
		"vgatherdpd":        {AVX, SIMD},
		"vgatherdps":        {AVX, SIMD},
		"vgatherqpd":        {AVX, SIMD},
		"vgatherqps":        {AVX, SIMD},
		"vinserti128":       {AVX, SIMD},
		"vpblendd":          {AVX, SIMD},
		"vpbroadcastb":      {AVX, SIMD},
		"vpbroadcastd":      {AVX, SIMD},
		"vpbroadcastq":      {AVX, SIMD},
		"vpbroadcastw":      {AVX, SIMD},
		"vperm2i128":        {AVX, SIMD},
		"vpermd":            {AVX, SIMD},
		"vpermpd":           {AVX, SIMD},
		"vpermps":           {AVX, SIMD},
		"vpermq":            {AVX, SIMD},
		"vpgatherdd":        {AVX, SIMD},
		"vpgatherdq":        {AVX, SIMD},
		"vpgatherqd":        {AVX, SIMD},
		"vpgatherqq":        {AVX, SIMD},
		"vpmaskmovd":        {AVX, SIMD},
		"vpmaskmovq":        {AVX, SIMD},
		"vpsllvd":           {AVX, SIMD},
		"vpsllvq":           {AVX, SIMD},
		"vpsravd":           {AVX, SIMD},
		"vpsrlvd":           {AVX, SIMD},
		"vpsrlvq":           {AVX, SIMD},
		"vcvtph2ps":         {AVX, SIMD},
		"vcvtps2ph":         {AVX, SIMD},
		"vfmadd132sd":       {AVX, SCALAR},
		"vfmadd132ss":       {AVX, SCALAR},
		"vfmadd213sd":       {AVX, SCALAR},
		"vfmadd213ss":       {AVX, SCALAR},
		"vfmadd231sd":       {AVX, SCALAR},
		"vfmadd231ss":       {AVX, SCALAR},
		"vfmsub132sd":       {AVX, SCALAR},
		"vfmsub132ss":       {AVX, SCALAR},
		"vfmsub213sd":       {AVX, SCALAR},
		"vfmsub213ss":       {AVX, SCALAR},
		"vfmsub231sd":       {AVX, SCALAR},
		"vfmsub231ss":       {AVX, SCALAR},
		"vfnmadd132sd":      {AVX, SCALAR},
		"vfnmadd132ss":      {AVX, SCALAR},
		"vfnmadd213sd":      {AVX, SCALAR},
		"vfnmadd213ss":      {AVX, SCALAR},
		"vfnmadd231sd":      {AVX, SCALAR},
		"vfnmadd231ss":      {AVX, SCALAR},
		"vfnmsub132sd":      {AVX, SCALAR},
		"vfnmsub132ss":      {AVX, SCALAR},
		"vfnmsub213sd":      {AVX, SCALAR},
		"vfnmsub213ss":      {AVX, SCALAR},
		"vfnmsub231sd":      {AVX, SCALAR},
		"vfnmsub231ss":      {AVX, SCALAR},
		"vfmadd132pd":       {AVX, SIMD},
		"vfmadd132ps":       {AVX, SIMD},
		"vfmadd213pd":       {AVX, SIMD},
		"vfmadd213ps":       {AVX, SIMD},
		"vfmadd231pd":       {AVX, SIMD},
		"vfmadd231ps":       {AVX, SIMD},
		"vfmaddsub132pd":    {AVX, SIMD},
		"vfmaddsub132ps":    {AVX, SIMD},
		"vfmaddsub213pd":    {AVX, SIMD},
		"vfmaddsub213ps":    {AVX, SIMD},
		"vfmaddsub231pd":    {AVX, SIMD},
		"vfmaddsub231ps":    {AVX, SIMD},
		"vfmsub132pd":       {AVX, SIMD},
		"vfmsub132ps":       {AVX, SIMD},
		"vfmsub213pd":       {AVX, SIMD},
		"vfmsub213ps":       {AVX, SIMD},
		"vfmsub231pd":       {AVX, SIMD},
		"vfmsub231ps":       {AVX, SIMD},
		"vfmsubadd132pd":    {AVX, SIMD},
		"vfmsubadd132ps":    {AVX, SIMD},
		"vfmsubadd213pd":    {AVX, SIMD},
		"vfmsubadd213ps":    {AVX, SIMD},
		"vfmsubadd231pd":    {AVX, SIMD},
		"vfmsubadd231ps":    {AVX, SIMD},
		"vfnmadd132pd":      {AVX, SIMD},
		"vfnmadd132ps":      {AVX, SIMD},
		"vfnmadd213pd":      {AVX, SIMD},
		"vfnmadd213ps":      {AVX, SIMD},
		"vfnmadd231pd":      {AVX, SIMD},
		"vfnmadd231ps":      {AVX, SIMD},
		"vfnmsub132pd":      {AVX, SIMD},
		"vfnmsub132ps":      {AVX, SIMD},
		"vfnmsub213pd":      {AVX, SIMD},
		"vfnmsub213ps":      {AVX, SIMD},
		"vfnmsub231pd":      {AVX, SIMD},
		"vfnmsub231ps":      {AVX, SIMD},
		"vfmaddsd":          {AVX, SCALAR},
		"vfmaddss":          {AVX, SCALAR},
		"vfmsubsd":          {AVX, SCALAR},
		"vfmsubss":          {AVX, SCALAR},
		"vfnmaddsd":         {AVX, SCALAR},
		"vfnmaddss":         {AVX, SCALAR},
		"vfnmsubsd":         {AVX, SCALAR},
		"vfnmsubss":         {AVX, SCALAR},
		"vfmaddpd":          {AVX, SIMD},
		"vfmaddps":          {AVX, SIMD},
		"vfmaddsubpd":       {AVX, SIMD},
		"vfmaddsubps":       {AVX, SIMD},
		"vfmsubaddpd":       {AVX, SIMD},
		"vfmsubaddps":       {AVX, SIMD},
		"vfmsubpd":          {AVX, SIMD},
		"vfmsubps":          {AVX, SIMD},
		"vfnmaddpd":         {AVX, SIMD},
		"vfnmaddps":         {AVX, SIMD},
		"vfnmsubpd":         {AVX, SIMD},
		"vfnmsubps":         {AVX, SIMD},
		"vfrczsd":           {AVX, SCALAR},
		"vfrczss":           {AVX, SCALAR},
		"vfrczpd":           {AVX, SIMD},
		"vfrczps":           {AVX, SIMD},
		"vpcmov":            {AVX, SIMD},
		"vpcomb":            {AVX, SIMD},
		"vpcomd":            {AVX, SIMD},
		"vpcomq":            {AVX, SIMD},
		"vpcomub":           {AVX, SIMD},
		"vpcomud":           {AVX, SIMD},
		"vpcomuq":           {AVX, SIMD},
		"vpcomuw":           {AVX, SIMD},
		"vpcomw":            {AVX, SIMD},
		"vpermil2pd":        {AVX, SIMD},
		"vpermil2ps":        {AVX, SIMD},
		"vphaddbd":          {AVX, SIMD},
		"vphaddbq":          {AVX, SIMD},
		"vphaddbw":          {AVX, SIMD},
		"vphadddq":          {AVX, SIMD},
		"vphaddubd":         {AVX, SIMD},
		"vphaddubq":         {AVX, SIMD},
		"vphaddubw":         {AVX, SIMD},
		"vphaddudq":         {AVX, SIMD},
		"vphadduwd":         {AVX, SIMD},
		"vphadduwq":         {AVX, SIMD},
		"vphaddwd":          {AVX, SIMD},
		"vphaddwq":          {AVX, SIMD},
		"vphsubbw":          {AVX, SIMD},
		"vphsubdq":          {AVX, SIMD},
		"vphsubwd":          {AVX, SIMD},
		"vpmacsdd":          {AVX, SIMD},
		"vpmacsdqh":         {AVX, SIMD},
		"vpmacsdql":         {AVX, SIMD},
		"vpmacssdd":         {AVX, SIMD},
		"vpmacssdqh":        {AVX, SIMD},
		"vpmacssdql":        {AVX, SIMD},
		"vpmacsswd":         {AVX, SIMD},
		"vpmacssww":         {AVX, SIMD},
		"vpmacswd":          {AVX, SIMD},
		"vpmacsww":          {AVX, SIMD},
		"vpmadcsswd":        {AVX, SIMD},
		"vpmadcswd":         {AVX, SIMD},
		"vpperm":            {AVX, SIMD},
		"vprotb":            {AVX, SIMD},
		"vprotd":            {AVX, SIMD},
		"vprotq":            {AVX, SIMD},
		"vprotw":            {AVX, SIMD},
		"vpshab":            {AVX, SIMD},
		"vpshad":            {AVX, SIMD},
		"vpshaq":            {AVX, SIMD},
		"vpshaw":            {AVX, SIMD},
		"vpshlb":            {AVX, SIMD},
		"vpshld":            {AVX, SIMD},
		"vpshlq":            {AVX, SIMD},
		"vpshlw":            {AVX, SIMD},
		"vpmadd52huq":       {AVX, SIMD},
		"vpmadd52luq":       {AVX, SIMD},
		"vbcstnebf162ps":    {AVX, SIMD},
		"vbcstnesh2ps":      {AVX, SIMD},
		"vcvtneebf162ps":    {AVX, SIMD},
		"vcvtneeph2ps":      {AVX, SIMD},
		"vcvtneobf162ps":    {AVX, SIMD},
		"vcvtneoph2ps":      {AVX, SIMD},
		"vcvtneps2bf16":     {AVX, SIMD},
		"vsha512msg1":       {AVX, SIMD},
		"vsha512msg2":       {AVX, SIMD},
		"vsha512rnds2":      {AVX, SIMD},
		"vsm3msg1":          {AVX, SIMD},
		"vsm3msg2":          {AVX, SIMD},
		"vsm3rnds2":         {AVX, SIMD},
		"vsm4key4":          {AVX, SIMD},
		"vsm4rnds4":         {AVX, SIMD},
		"vpdpbusd":          {AVX, SIMD},
		"vpdpbusds":         {AVX, SIMD},
		"vpdpwssd":          {AVX, SIMD},
		"vpdpwssds":         {AVX, SIMD},
		"vpdpbssd":          {AVX, SIMD},
		"vpdpbssds":         {AVX, SIMD},
		"vpdpbsud":          {AVX, SIMD},
		"vpdpbsuds":         {AVX, SIMD},
		"vpdpbuud":          {AVX, SIMD},
		"vpdpbuuds":         {AVX, SIMD},
		"vpdpwsud":          {AVX, SIMD},
		"vpdpwsuds":         {AVX, SIMD},
		"vpdpwusd":          {AVX, SIMD},
		"vpdpwusds":         {AVX, SIMD},
		"vpdpwuud":          {AVX, SIMD},
		"vpdpwuuds":         {AVX, SIMD},
		"kandnw":            {AVX512, MASK},
		"kandw":             {AVX512, MASK},
		"kmovw":             {AVX512, MASK},
		"knotw":             {AVX512, MASK},
		"kortestw":          {AVX512, MASK},
		"korw":              {AVX512, MASK},
		"kshiftlw":          {AVX512, MASK},
		"kshiftrw":          {AVX512, MASK},
		"kunpckbw":          {AVX512, MASK},
		"kxnorw":            {AVX512, MASK},
		"kxorw":             {AVX512, MASK},
		"kaddb":             {AVX512, MASK},
		"kaddw":             {AVX512, MASK},
		"kandb":             {AVX512, MASK},
		"kandnb":            {AVX512, MASK},
		"kmovb":             {AVX512, MASK},
		"knotb":             {AVX512, MASK},
		"korb":              {AVX512, MASK},
		"kortestb":          {AVX512, MASK},
		"kshiftlb":          {AVX512, MASK},
		"kshiftrb":          {AVX512, MASK},
		"ktestb":            {AVX512, MASK},
		"ktestw":            {AVX512, MASK},
		"kxnorb":            {AVX512, MASK},
		"kxorb":             {AVX512, MASK},
		"kaddd":             {AVX512, MASK},
		"kaddq":             {AVX512, MASK},
		"kandd":             {AVX512, MASK},
		"kandnd":            {AVX512, MASK},
		"kandnq":            {AVX512, MASK},
		"kandq":             {AVX512, MASK},
		"kmovd":             {AVX512, MASK},
		"kmovq":             {AVX512, MASK},
		"knotd":             {AVX512, MASK},
		"knotq":             {AVX512, MASK},
		"kord":              {AVX512, MASK},
		"korq":              {AVX512, MASK},
		"kortestd":          {AVX512, MASK},
		"kortestq":          {AVX512, MASK},
		"kshiftld":          {AVX512, MASK},
		"kshiftlq":          {AVX512, MASK},
		"kshiftrd":          {AVX512, MASK},
		"kshiftrq":          {AVX512, MASK},
		"ktestd":            {AVX512, MASK},
		"ktestq":            {AVX512, MASK},
		"kunpckdq":          {AVX512, MASK},
		"kunpckwd":          {AVX512, MASK},
		"kxnord":            {AVX512, MASK},
		"kxnorq":            {AVX512, MASK},
		"kxord":             {AVX512, MASK},
		"kxorq":             {AVX512, MASK},
		"vcvtsd2usi":        {AVX512, SCALAR},
		"vcvtss2usi":        {AVX512, SCALAR},
		"vcvttsd2usi":       {AVX512, SCALAR},
		"vcvttss2usi":       {AVX512, SCALAR},
		"vcvtusi2sd":        {AVX512, SCALAR},
		"vcvtusi2ss":        {AVX512, SCALAR},
		"vfixupimmsd":       {AVX512, SCALAR},
		"vfixupimmss":       {AVX512, SCALAR},
		"vgetexpsd":         {AVX512, SCALAR},
		"vgetexpss":         {AVX512, SCALAR},
		"vgetmantsd":        {AVX512, SCALAR},
		"vgetmantss":        {AVX512, SCALAR},
		"vrcp14sd":          {AVX512, SCALAR},
		"vrcp14ss":          {AVX512, SCALAR},
		"vrndscalesd":       {AVX512, SCALAR},
		"vrndscaless":       {AVX512, SCALAR},
		"vrsqrt14sd":        {AVX512, SCALAR},
		"vrsqrt14ss":        {AVX512, SCALAR},
		"vscalefsd":         {AVX512, SCALAR},
		"vscalefss":         {AVX512, SCALAR},
		"valignd":           {AVX512, SIMD},
		"valignq":           {AVX512, SIMD},
		"vblendmpd":         {AVX512, SIMD},
		"vblendmps":         {AVX512, SIMD},
		"vbroadcastf32x4":   {AVX512, SIMD},
		"vbroadcastf64x4":   {AVX512, SIMD},
		"vbroadcasti32x4":   {AVX512, SIMD},
		"vbroadcasti64x4":   {AVX512, SIMD},
		"vcompresspd":       {AVX512, SIMD},
		"vcompressps":       {AVX512, SIMD},
		"vcvtpd2udq":        {AVX512, SIMD},
		"vcvtps2udq":        {AVX512, SIMD},
		"vcvttpd2qq":        {AVX512, SIMD},
		"vcvttpd2udq":       {AVX512, SIMD},
		"vcvttps2udq":       {AVX512, SIMD},
		"vcvtudq2pd":        {AVX512, SIMD},
		"vcvtudq2ps":        {AVX512, SIMD},
		"vexpandpd":         {AVX512, SIMD},
		"vexpandps":         {AVX512, SIMD},
		"vextractf32x4":     {AVX512, SIMD},
		"vextractf64x4":     {AVX512, SIMD},
		"vextracti32x4":     {AVX512, SIMD},
		"vextracti64x4":     {AVX512, SIMD},
		"vfixupimmpd":       {AVX512, SIMD},
		"vfixupimmps":       {AVX512, SIMD},
		"vgetexppd":         {AVX512, SIMD},
		"vgetexpps":         {AVX512, SIMD},
		"vgetmantpd":        {AVX512, SIMD},
		"vgetmantps":        {AVX512, SIMD},
		"vinsertf32x4":      {AVX512, SIMD},
		"vinsertf64x4":      {AVX512, SIMD},
		"vinserti32x4":      {AVX512, SIMD},
		"vinserti64x4":      {AVX512, SIMD},
		"vmovdqa32":         {AVX512, SIMD},
		"vmovdqa64":         {AVX512, SIMD},
		"vmovdqu32":         {AVX512, SIMD},
		"vmovdqu64":         {AVX512, SIMD},
		"vpabsq":            {AVX512, SIMD},
		"vpandd":            {AVX512, SIMD},
		"vpandnd":           {AVX512, SIMD},
		"vpandnq":           {AVX512, SIMD},
		"vpandq":            {AVX512, SIMD},
		"vpblendmd":         {AVX512, SIMD},
		"vpblendmq":         {AVX512, SIMD},
		"vpcmpd":            {AVX512, SIMD},
		"vpcmpq":            {AVX512, SIMD},
		"vpcmpud":           {AVX512, SIMD},
		"vpcmpuq":           {AVX512, SIMD},
		"vpcompressd":       {AVX512, SIMD},
		"vpcompressq":       {AVX512, SIMD},
		"vpermi2d":          {AVX512, SIMD},
		"vpermi2pd":         {AVX512, SIMD},
		"vpermi2ps":         {AVX512, SIMD},
		"vpermi2q":          {AVX512, SIMD},
		"vpermt2d":          {AVX512, SIMD},
		"vpermt2pd":         {AVX512, SIMD},
		"vpermt2ps":         {AVX512, SIMD},
		"vpermt2q":          {AVX512, SIMD},
		"vpexpandd":         {AVX512, SIMD},
		"vpexpandq":         {AVX512, SIMD},
		"vpmaxsq":           {AVX512, SIMD},
		"vpmaxuq":           {AVX512, SIMD},
		"vpminsq":           {AVX512, SIMD},
		"vpminuq":           {AVX512, SIMD},
		"vpmovdb":           {AVX512, SIMD},
		"vpmovdw":           {AVX512, SIMD},
		"vpmovqb":           {AVX512, SIMD},
		"vpmovqd":           {AVX512, SIMD},
		"vpmovqw":           {AVX512, SIMD},
		"vpmovsdb":          {AVX512, SIMD},
		"vpmovsdw":          {AVX512, SIMD},
		"vpmovsqb":          {AVX512, SIMD},
		"vpmovsqd":          {AVX512, SIMD},
		"vpmovsqw":          {AVX512, SIMD},
		"vpmovusdb":         {AVX512, SIMD},
		"vpmovusdw":         {AVX512, SIMD},
		"vpmovusqb":         {AVX512, SIMD},
		"vpmovusqd":         {AVX512, SIMD},
		"vpmovusqw":         {AVX512, SIMD},
		"vpord":             {AVX512, SIMD},
		"vporq":             {AVX512, SIMD},
		"vprold":            {AVX512, SIMD},
		"vprolq":            {AVX512, SIMD},
		"vprolvd":           {AVX512, SIMD},
		"vprolvq":           {AVX512, SIMD},
		"vprord":            {AVX512, SIMD},
		"vprorq":            {AVX512, SIMD},
		"vprorvd":           {AVX512, SIMD},
		"vprorvq":           {AVX512, SIMD},
		"vpscatterdd":       {AVX512, SIMD},
		"vpscatterdq":       {AVX512, SIMD},
		"cmpnlesd":          {AVX512, SIMD},
		"vpscatterqd":       {AVX512, SIMD},
		"vpscatterqq":       {AVX512, SIMD},
		"vpsraq":            {AVX512, SIMD},
		"vpsravq":           {AVX512, SIMD},
		"vpternlogd":        {AVX512, SIMD},
		"vpternlogq":        {AVX512, SIMD},
		"vptestmd":          {AVX512, SIMD},
		"vptestmq":          {AVX512, SIMD},
		"vptestnmd":         {AVX512, SIMD},
		"vptestnmq":         {AVX512, SIMD},
		"vpxord":            {AVX512, SIMD},
		"vpxorq":            {AVX512, SIMD},
		"vrcp14pd":          {AVX512, SIMD},
		"vrcp14ps":          {AVX512, SIMD},
		"vrndscalepd":       {AVX512, SIMD},
		"vrndscaleps":       {AVX512, SIMD},
		"vrsqrt14pd":        {AVX512, SIMD},
		"vrsqrt14ps":        {AVX512, SIMD},
		"vscalefpd":         {AVX512, SIMD},
		"vscalefps":         {AVX512, SIMD},
		"vscatterdpd":       {AVX512, SIMD},
		"vscatterdps":       {AVX512, SIMD},
		"vscatterqpd":       {AVX512, SIMD},
		"vscatterqps":       {AVX512, SIMD},
		"vshuff32x4":        {AVX512, SIMD},
		"vshuff64x2":        {AVX512, SIMD},
		"vshufi32x4":        {AVX512, SIMD},
		"vshufi64x2":        {AVX512, SIMD},
		"vfpclasssd":        {AVX512, SCALAR},
		"vfpclassss":        {AVX512, SCALAR},
		"vrangesd":          {AVX512, SCALAR},
		"vrangess":          {AVX512, SCALAR},
		"vreducesd":         {AVX512, SCALAR},
		"vreducess":         {AVX512, SCALAR},
		"vbroadcastf32x2":   {AVX512, SIMD},
		"vbroadcastf32x8":   {AVX512, SIMD},
		"vbroadcastf64x2":   {AVX512, SIMD},
		"vbroadcasti32x2":   {AVX512, SIMD},
		"vbroadcasti32x8":   {AVX512, SIMD},
		"vbroadcasti64x2":   {AVX512, SIMD},
		"vcvtpd2qq":         {AVX512, SIMD},
		"vcvtpd2uqq":        {AVX512, SIMD},
		"vcvtps2qq":         {AVX512, SIMD},
		"vcvtps2uqq":        {AVX512, SIMD},
		"vcvtqq2pd":         {AVX512, SIMD},
		"vcvtqq2ps":         {AVX512, SIMD},
		"vcvttpd2uqq":       {AVX512, SIMD},
		"vcvttps2qq":        {AVX512, SIMD},
		"vcvttps2uqq":       {AVX512, SIMD},
		"vcvtuqq2pd":        {AVX512, SIMD},
		"vcvtuqq2ps":        {AVX512, SIMD},
		"vextractf32x8":     {AVX512, SIMD},
		"vextractf64x2":     {AVX512, SIMD},
		"vextracti32x8":     {AVX512, SIMD},
		"vextracti64x2":     {AVX512, SIMD},
		"vfpclasspd":        {AVX512, SIMD},
		"vfpclassps":        {AVX512, SIMD},
		"vinsertf32x8":      {AVX512, SIMD},
		"vinsertf64x2":      {AVX512, SIMD},
		"vinserti32x8":      {AVX512, SIMD},
		"vinserti64x2":      {AVX512, SIMD},
		"vpmovd2m":          {AVX512, SIMD},
		"vpmovm2d":          {AVX512, SIMD},
		"vpmovm2q":          {AVX512, SIMD},
		"vpmovq2m":          {AVX512, SIMD},
		"vpmullq":           {AVX512, SIMD},
		"vrangepd":          {AVX512, SIMD},
		"vrangeps":          {AVX512, SIMD},
		"vreducepd":         {AVX512, SIMD},
		"vreduceps":         {AVX512, SIMD},
		"vdbpsadbw":         {AVX512, SIMD},
		"vmovdqu16":         {AVX512, SIMD},
		"vmovdqu8":          {AVX512, SIMD},
		"vpblendmb":         {AVX512, SIMD},
		"vpblendmw":         {AVX512, SIMD},
		"vpcmpb":            {AVX512, SIMD},
		"vpcmpub":           {AVX512, SIMD},
		"vpcmpuw":           {AVX512, SIMD},
		"vpcmpw":            {AVX512, SIMD},
		"vpermi2w":          {AVX512, SIMD},
		"vpermt2w":          {AVX512, SIMD},
		"vpermw":            {AVX512, SIMD},
		"vpmovb2m":          {AVX512, SIMD},
		"vpmovm2b":          {AVX512, SIMD},
		"vpmovm2w":          {AVX512, SIMD},
		"vpmovswb":          {AVX512, SIMD},
		"vpmovuswb":         {AVX512, SIMD},
		"vpmovw2m":          {AVX512, SIMD},
		"vpmovwb":           {AVX512, SIMD},
		"vpsllvw":           {AVX512, SIMD},
		"vpsravw":           {AVX512, SIMD},
		"vpsrlvw":           {AVX512, SIMD},
		"vptestmb":          {AVX512, SIMD},
		"vptestmw":          {AVX512, SIMD},
		"vptestnmb":         {AVX512, SIMD},
		"vptestnmw":         {AVX512, SIMD},
		"vpbroadcastmb2q":   {AVX512, SIMD},
		"vpbroadcastmw2d":   {AVX512, SIMD},
		"vpconflictd":       {AVX512, SIMD},
		"vpconflictq":       {AVX512, SIMD},
		"vplzcntd":          {AVX512, SIMD},
		"vplzcntq":          {AVX512, SIMD},
		"vrcp28sd":          {AVX512, SCALAR},
		"vrcp28ss":          {AVX512, SCALAR},
		"vrsqrt28sd":        {AVX512, SCALAR},
		"vrsqrt28ss":        {AVX512, SCALAR},
		"vrcp28pd":          {AVX512, SIMD},
		"vrcp28ps":          {AVX512, SIMD},
		"vrsqrt28pd":        {AVX512, SIMD},
		"vrsqrt28ps":        {AVX512, SIMD},
		"vexp2pd":           {AVX512, SIMD},
		"vexp2ps":           {AVX512, SIMD},
		"vgatherpf0dpd":     {AVX512, SIMD},
		"vgatherpf0dps":     {AVX512, SIMD},
		"vgatherpf0qpd":     {AVX512, SIMD},
		"vgatherpf0qps":     {AVX512, SIMD},
		"vgatherpf1dpd":     {AVX512, SIMD},
		"vgatherpf1dps":     {AVX512, SIMD},
		"vgatherpf1qpd":     {AVX512, SIMD},
		"vgatherpf1qps":     {AVX512, SIMD},
		"vscatterpf0dpd":    {AVX512, SIMD},
		"vscatterpf0dps":    {AVX512, SIMD},
		"vscatterpf0qpd":    {AVX512, SIMD},
		"vscatterpf0qps":    {AVX512, SIMD},
		"vscatterpf1dpd":    {AVX512, SIMD},
		"vscatterpf1dps":    {AVX512, SIMD},
		"vscatterpf1qpd":    {AVX512, SIMD},
		"vscatterpf1qps":    {AVX512, SIMD},
		"vpopcntd":          {AVX512, SIMD},
		"vpopcntq":          {AVX512, SIMD},
		"vpermb":            {AVX512, SIMD},
		"vpermi2b":          {AVX512, SIMD},
		"vpermt2b":          {AVX512, SIMD},
		"vpmultishiftqb":    {AVX512, SIMD},
		"vpcompressb":       {AVX512, SIMD},
		"vpcompressw":       {AVX512, SIMD},
		"vpexpandb":         {AVX512, SIMD},
		"vpexpandw":         {AVX512, SIMD},
		"vpshldd":           {AVX512, SIMD},
		"vpshldq":           {AVX512, SIMD},
		"vpshldvd":          {AVX512, SIMD},
		"vpshldvq":          {AVX512, SIMD},
		"vpshldvw":          {AVX512, SIMD},
		"vpshldw":           {AVX512, SIMD},
		"vpshrdd":           {AVX512, SIMD},
		"vpshrdq":           {AVX512, SIMD},
		"vpshrdvd":          {AVX512, SIMD},
		"vpshrdvq":          {AVX512, SIMD},
		"vpshrdvw":          {AVX512, SIMD},
		"vpshrdw":           {AVX512, SIMD},
		"v4fmaddps":         {AVX512, SIMD},
		"v4fmaddss":         {AVX512, SIMD},
		"v4fnmaddps":        {AVX512, SIMD},
		"v4fnmaddss":        {AVX512, SIMD},
		"vp4dpwssd":         {AVX512, SIMD},
		"vp4dpwssds":        {AVX512, SIMD},
		"vpopcntb":          {AVX512, SIMD},
		"vpopcntw":          {AVX512, SIMD},
		"vpshufbitqmb":      {AVX512, SIMD},
		"vp2intersectd":     {AVX512, SIMD},
		"vp2intersectq":     {AVX512, SIMD},
		"vcvtne2ps2bf16":    {AVX512, SIMD},
		"vdpbf16ps":         {AVX512, SIMD},
		"vaddsh":            {AVX512, SCALAR},
		"vcmpsh":            {AVX512, SCALAR},
		"vcomish":           {AVX512, SCALAR},
		"vcvtsd2sh":         {AVX512, SCALAR},
		"vcvtsh2sd":         {AVX512, SCALAR},
		"vcvtsh2si":         {AVX512, SCALAR},
		"vcvtsh2ss":         {AVX512, SCALAR},
		"vcvtsh2usi":        {AVX512, SCALAR},
		"vcvtsi2sh":         {AVX512, SCALAR},
		"vcvtss2sh":         {AVX512, SCALAR},
		"vcvttsh2si":        {AVX512, SCALAR},
		"vcvttsh2usi":       {AVX512, SCALAR},
		"vcvtusi2sh":        {AVX512, SCALAR},
		"vdivsh":            {AVX512, SCALAR},
		"vfmadd132sh":       {AVX512, SCALAR},
		"vfmadd213sh":       {AVX512, SCALAR},
		"vfmadd231sh":       {AVX512, SCALAR},
		"vfmsub132sh":       {AVX512, SCALAR},
		"vfmsub213sh":       {AVX512, SCALAR},
		"vfmsub231sh":       {AVX512, SCALAR},
		"vfnmadd132sh":      {AVX512, SCALAR},
		"vfnmadd213sh":      {AVX512, SCALAR},
		"vfnmadd231sh":      {AVX512, SCALAR},
		"vfnmsub132sh":      {AVX512, SCALAR},
		"vfnmsub213sh":      {AVX512, SCALAR},
		"vfnmsub231sh":      {AVX512, SCALAR},
		"vfpclasssh":        {AVX512, SCALAR},
		"vgetexpsh":         {AVX512, SCALAR},
		"vgetmantsh":        {AVX512, SCALAR},
		"vmaxsh":            {AVX512, SCALAR},
		"vminsh":            {AVX512, SCALAR},
		"vmovsh":            {AVX512, SCALAR},
		"vmulsh":            {AVX512, SCALAR},
		"vrcpsh":            {AVX512, SCALAR},
		"vreducesh":         {AVX512, SCALAR},
		"vrndscalesh":       {AVX512, SCALAR},
		"vrsqrtsh":          {AVX512, SCALAR},
		"vscalefsh":         {AVX512, SCALAR},
		"vsqrtsh":           {AVX512, SCALAR},
		"vsubsh":            {AVX512, SCALAR},
		"vucomish":          {AVX512, SCALAR},
		"vfcmaddcsh":        {AVX512, SCALAR},
		"vfcmulcsh":         {AVX512, SCALAR},
		"vfmaddcsh":         {AVX512, SCALAR},
		"vaddph":            {AVX512, SIMD},
		"vcmpph":            {AVX512, SIMD},
		"vcvtdq2ph":         {AVX512, SIMD},
		"vcvtpd2ph":         {AVX512, SIMD},
		"vcvtph2dq":         {AVX512, SIMD},
		"vcvtph2pd":         {AVX512, SIMD},
		"vcvtph2psx":        {AVX512, SIMD},
		"vcvtph2qq":         {AVX512, SIMD},
		"vcvtph2udq":        {AVX512, SIMD},
		"vcvtph2uqq":        {AVX512, SIMD},
		"vcvtph2uw":         {AVX512, SIMD},
		"vcvtph2w":          {AVX512, SIMD},
		"vcvtps2phx":        {AVX512, SIMD},
		"vcvtqq2ph":         {AVX512, SIMD},
		"vcvttph2dq":        {AVX512, SIMD},
		"vcvttph2qq":        {AVX512, SIMD},
		"vcvttph2udq":       {AVX512, SIMD},
		"vcvttph2uqq":       {AVX512, SIMD},
		"vcvttph2uw":        {AVX512, SIMD},
		"vcvttph2w":         {AVX512, SIMD},
		"vcvtudq2ph":        {AVX512, SIMD},
		"vcvtuqq2ph":        {AVX512, SIMD},
		"vcvtuw2ph":         {AVX512, SIMD},
		"vcvtw2ph":          {AVX512, SIMD},
		"vdivph":            {AVX512, SIMD},
		"vfcmaddcph":        {AVX512, SIMD},
		"vfcmulcph":         {AVX512, SIMD},
		"vfmadd132ph":       {AVX512, SIMD},
		"vfmadd213ph":       {AVX512, SIMD},
		"vfmadd231ph":       {AVX512, SIMD},
		"vfmaddcph":         {AVX512, SIMD},
		"vfmaddsub132ph":    {AVX512, SIMD},
		"vfmaddsub213ph":    {AVX512, SIMD},
		"vfmaddsub231ph":    {AVX512, SIMD},
		"vfmsub132ph":       {AVX512, SIMD},
		"vfmsub213ph":       {AVX512, SIMD},
		"vfmsub231ph":       {AVX512, SIMD},
		"vfmsubadd132ph":    {AVX512, SIMD},
		"vfmsubadd213ph":    {AVX512, SIMD},
		"vfmsubadd231ph":    {AVX512, SIMD},
		"vfmulcph":          {AVX512, SIMD},
		"vfmulcsh":          {AVX512, SIMD},
		"vfnmadd132ph":      {AVX512, SIMD},
		"vfnmadd213ph":      {AVX512, SIMD},
		"vfnmadd231ph":      {AVX512, SIMD},
		"vfnmsub132ph":      {AVX512, SIMD},
		"vfnmsub213ph":      {AVX512, SIMD},
		"vfnmsub231ph":      {AVX512, SIMD},
		"vfpclassph":        {AVX512, SIMD},
		"vgetexpph":         {AVX512, SIMD},
		"vgetmantph":        {AVX512, SIMD},
		"vmaxph":            {AVX512, SIMD},
		"vminph":            {AVX512, SIMD},
		"vmovw":             {AVX512, SIMD},
		"vmulph":            {AVX512, SIMD},
		"vrcpph":            {AVX512, SIMD},
		"vreduceph":         {AVX512, SIMD},
		"vrndscaleph":       {AVX512, SIMD},
		"vrsqrtph":          {AVX512, SIMD},
		"vscalefph":         {AVX512, SIMD},
		"vsqrtph":           {AVX512, SIMD},
		"vsubph":            {AVX512, SIMD},
		"ldtilecfg":         {AMX},
		"sttilecfg":         {AMX},
		"tileloadd":         {AMX},
		"tileloaddt1":       {AMX},
		"tilerelease":       {AMX},
		"tilestored":        {AMX},
		"tilezero":          {AMX},
		"tdpbf16ps":         {AMX},
		"tcmmimfp16ps":      {AMX},
		"tcmmrlfp16ps":      {AMX},
		"tdpfp16ps":         {AMX},
		"tdpbssd":           {AMX},
		"tdpbsud":           {AMX},
		"tdpbusd":           {AMX},
		"tdpbuud":           {AMX},
	}
	X86X64ControlFlowInst = map[string]struct{}{
		"call":      {},
		"lcall":     {},
		"iret":      {},
		"iretd":     {},
		"iretq":     {},
		"jae":       {},
		"jnb":       {},
		"jnc":       {},
		"jo":        {},
		"jno":       {},
		"jb":        {},
		"jnae":      {},
		"jc":        {},
		"je":        {},
		"jz":        {},
		"jne":       {},
		"jnz":       {},
		"jbe":       {},
		"jna":       {},
		"ja":        {},
		"jnbe":      {},
		"js":        {},
		"jns":       {},
		"jp":        {},
		"jpe":       {},
		"jnp":       {},
		"jpo":       {},
		"jl":        {},
		"jnge":      {},
		"jge":       {},
		"jnl":       {},
		"jle":       {},
		"jng":       {},
		"jg":        {},
		"jnle":      {},
		"jecxz	jmp": {},
		"ljmp":      {},
		"loop":      {},
		"loope":     {},
		"loopne":    {},
		"ret":       {},
		"retf":      {},
	}
)
